/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpeso;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

/**
 *
 * @author Reymundo Tenorio
 */
public class ConsultarSaldoTUC extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarSaldoTUC
     */
    public ConsultarSaldoTUC() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTUC = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        Mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar saldo TUC");
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("No. Tarjeta TUC");

        try {
            txtTUC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTUC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTUC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTUCFocusGained(evt);
            }
        });
        txtTUC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTUCKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Mensaje.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Mensaje.setForeground(new java.awt.Color(255, 255, 255));
        Mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTUC, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtTUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addGap(6, 6, 6)
                .addComponent(Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(618, 187));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void Consultar() throws IOException {

        String NoTUC = txtTUC.getText().trim();

        if ("".equals(NoTUC)) {
            JOptionPane.showMessageDialog(this, "Ingrese el número de su tarjeta TUC", "Ingresar información", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Document document;
        document = Jsoup.connect("https://www.mpeso.net/datos/consulta.php")
                .data("_funcion", "1") //Funcion 1
                .data("_captcha", "5b39df") // Captcha introducido
                .data("_terminal", NoTUC) // No. TUC
                .data("_codigo", "5b39df") //Codio del captcha
                //                .cookies(loginForm.cookies())
                .post();

        String Saldo = Jsoup.parse(document.toString()).text();

        Mensaje.setForeground(Color.WHITE);

        System.out.println("Mensaje JSON: " + Saldo);

//        System.err.println(Saldo.trim());
        if ("".equals(Saldo)) {
            Saldo = "Ingrese correctamente tu número de tarjeta TUC";
            Mensaje.setForeground(Color.PINK);
            Mensaje.setText(Saldo);
            return;
        } else if ("{\"Error\":false,\"Mensaje\":\" Para consultar tu Saldo MPESO a trav\\u00e9s de un numero de celular, ingresa a tu cuenta<\\/a><\\/p>\"}".equals(Saldo.trim())) {
            Saldo = "No es un número de tarjeta TUC o está Inactivo";
            Mensaje.setForeground(Color.PINK);

        } else if ("{\"Error\":true,\"Mensaje\":\" No es un N\\u00famero de Tarjeta Tuc \\u00f3 Est\\u00e1 Inactivo Cont\\u00e1ctanos<\\/a><\\/p>\"}".equals(Saldo.trim())) {
            Saldo = "No es un número de tarjeta TUC o está Inactivo";
            Mensaje.setForeground(Color.PINK);
        } else {

            int Inicio = Saldo.indexOf("Su saldo MPESO");
            int Final = Saldo.indexOf("<\\/p>");

            System.out.println("Inicio: " + Inicio + " Final: " + Final);
            Saldo = Saldo.substring(Inicio, Final);
        }

//        System.out.println("Saldo: " + Saldo);
        Mensaje.setText(Saldo);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Consultar();
            // TODO add your handling code here:
        } catch (IOException ex) {
            System.err.println("Error al obtener saldo TUC: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTUCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTUCFocusGained
        txtTUC.setCaretPosition(0);        // TODO add your handling code here:
    }//GEN-LAST:event_txtTUCFocusGained

    private void txtTUCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTUCKeyTyped
        int Key = evt.getKeyChar();

        if (Key == KeyEvent.VK_ENTER) {
            try {
                Consultar();
            } catch (IOException ex) {
                System.err.println("Error al obtener saldo TUC: " + ex.getMessage());
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_txtTUCKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarSaldoTUC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarSaldoTUC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarSaldoTUC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarSaldoTUC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ConsultarSaldoTUC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mensaje;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField txtTUC;
    // End of variables declaration//GEN-END:variables
}
